site_name: Lanarky
site_url: https://lanarky.ajndkr.com/
site_author: Ajinkya Indulkar
site_description: The web framework for building LLM microservices
repo_name: ajndkr/lanarky
repo_url: https://github.com/ajndkr/lanarky
copyright: Copyright &copy; 2023 Ajinkya Indulkar

edit_uri: ""

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: lanarky
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - content.tabs.link
    - content.tooltips
    - content.code.annotate
    - content.code.copy
    - content.code.select
  icon:
    repo: fontawesome/brands/github-alt
  logo: assets/icon.svg
  favicon: assets/favicon.png
  language: en
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Lanarky: index.md
  - Getting Started: getting-started.md
  - Learn:
      - learn/index.md
      - Streaming: learn/streaming.md
      - WebSockets: learn/websockets.md
      - Adapters:
          - learn/adapters/index.md
          - OpenAI:
              - learn/adapters/openai/index.md
              - Router: learn/adapters/openai/router.md
              - Advanced:
                  - Dependency Injection: learn/adapters/openai/dependency.md
                  - FastAPI Backport: learn/adapters/openai/fastapi.md
          - LangChain:
              - learn/adapters/langchain/index.md
              - Router: learn/adapters/langchain/router.md
              - learn/adapters/langchain/callbacks.md
              - Advanced:
                  - Dependency Injection: learn/adapters/langchain/dependency.md
                  - FastAPI Backport: learn/adapters/langchain/fastapi.md
  - API Reference:
      - reference/index.md
      - Lanarky: reference/lanarky.md
      - Streaming: reference/streaming.md
      - WebSockets: reference/websockets.md
      - Adapters:
          - OpenAI: reference/adapters/openai.md
          - LangChain: reference/adapters/langchain.md
      - Miscellaneous: reference/misc.md

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - mdx_include:
      base_path: docs
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ajndkr
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/lanarky/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/LanarkyAPI

extra_css:
  - stylesheets/extra.css

plugins:
  - social
  - termynal
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: false
            inherited_members: true
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            merge_init_into_class: true
            show_source: false
